<?php
function arraySafeVal($a,$k,$d=null){return is_array($a)&&array_key_exists($k,$a)?$a[$k]:$d;}
require_once(dirname(__DIR__).'/web/yaamp/core/backend/BadpoolPaymentBatchPhaseAdapter.php');
function live_expect($ok,$message,&$fail){if(!$ok)$fail[]=$message;}
class LiveSelectionGuard {
	public $rows=array(); public $sql; public $params;
	public function selectAll($sql,$params){$this->sql=$sql;$this->params=$params;$excludedE=array();$excludedB=array();foreach($params as$key=>$value){if(strpos($key,':excluded_earning_')===0)$excludedE[]=intval($value);if(strpos($key,':excluded_block_')===0)$excludedB[]=intval($value);}$out=array();foreach($this->rows as $r){if(in_array(intval($r['earning_id']),$excludedE,true)||in_array(intval($r['block_id']),$excludedB,true)||intval($r['coin_id'])!==1267||intval($r['status'])!==1||$r['mature_time']===null||intval($r['block_coin_id'])!==1267||intval($r['block_id'])<=29242||$r['category']!=='generate'||empty($r['candidate'])||intval($r['candidate_coin_id'])!==1267||$r['candidate_algo']!=='scrypt'||$r['candidate_hash']!==$r['blockhash']||intval($r['account_coinid'])!==1267)continue;$out[]=array('earning_id'=>$r['earning_id'],'block_id'=>$r['block_id'],'account_id'=>$r['account_id'],'coin_id'=>$r['coin_id']);}usort($out,function($a,$b){return $a['earning_id']-$b['earning_id'];});if(preg_match('/ LIMIT ([0-9]+)$/',$sql,$m))$out=array_slice($out,0,intval($m[1]));return $out;}
}
function live_row($id,$block=29243){return array('earning_id'=>$id,'block_id'=>$block,'account_id'=>79,'coin_id'=>1267,'status'=>1,'mature_time'=>100,'block_coin_id'=>1267,'category'=>'generate','candidate'=>true,'candidate_coin_id'=>1267,'candidate_algo'=>'scrypt','candidate_hash'=>'h'.$block,'blockhash'=>'h'.$block,'account_coinid'=>1267);}
class GroestlSelectionGuard {public $rows=array(),$sql,$params;public function selectAll($sql,$params){$this->sql=$sql;$this->params=$params;$coin=intval($params[':coin']);$algo=$params[':algo'];$boundary=intval($params[':boundary']);$out=array();foreach($this->rows as $r){if(intval($r['coin_id'])!==$coin||intval($r['status'])!==1||$r['mature_time']===null||intval($r['block_coin_id'])!==$coin||intval($r['block_id'])<=$boundary||$r['category']!=='generate'||empty($r['candidate'])||intval($r['candidate_coin_id'])!==$coin||$r['candidate_algo']!==$algo||$r['candidate_hash']!==$r['blockhash']||intval($r['account_coinid'])!==$coin)continue;$out[]=array('earning_id'=>$r['earning_id'],'block_id'=>$r['block_id'],'account_id'=>$r['account_id'],'coin_id'=>$r['coin_id']);}usort($out,function($a,$b){return $a['earning_id']-$b['earning_id'];});if(preg_match('/ LIMIT ([0-9]+)$/',$sql,$m))$out=array_slice($out,0,intval($m[1]));return $out;}}
function groestl_row($id,$block=31213){return array('earning_id'=>$id,'block_id'=>$block,'account_id'=>81,'coin_id'=>1269,'status'=>1,'mature_time'=>100,'block_coin_id'=>1269,'category'=>'generate','candidate'=>true,'candidate_coin_id'=>1269,'candidate_algo'=>'badcoin-groestl','candidate_hash'=>'g'.$block,'blockhash'=>'g'.$block,'account_coinid'=>1269);}
class LiveDelayExecutor {public $returned=array();public $calls=array();public function run($command,$args){$this->calls[]=array($command,$args);$items=array();foreach($this->returned as $id)$items[]=array('earning_id'=>$id);return array('status'=>'pass','items'=>array('selected_earnings'=>$items));}}
$fail=array();$root=sys_get_temp_dir().'/badpool-live-status1-'.getmypid();mkdir($root,0770,true);$ledger=array('mode'=>'auto','run_directory'=>$root,'selected_coin_scope'=>array(array('id'=>1267)));
$g=new LiveSelectionGuard();$g->rows=array(live_row(20,29244),live_row(10,29243));$a=new BadpoolPaymentBatchPhaseAdapter($g,function(){});$r=$a->selectEligibleWork($ledger,array('mode'=>'auto','batch_size'=>1));
live_expect($r['selected_earning_ids']===array(10),'live row ordering or batch bound failed',$fail);live_expect($r['selected_block_ids']===array(29243)&&$r['selected_account_ids']===array(79),'durable block/account scope failed',$fail);
foreach(array('E.coinid=:coin','E.status=1','E.mature_time IS NOT NULL','B.id>:boundary',"B.category='generate'",'C.block_id=B.id','C.coin_id=B.coin_id','C.algo=:algo','C.blockhash=B.blockhash','A.id=E.userid','A.coinid=:coin','ORDER BY E.id','LIMIT 1') as $term)live_expect(strpos($g->sql,$term)!==false,'selector SQL missing '.$term,$fail);
live_expect($g->params===array(':coin'=>1267,':algo'=>'scrypt',':boundary'=>29242),'fixed live selector parameters drifted',$fail);
$g->rows=array(live_row(10,29243),live_row(20,29244));$excluded=$a->selectEligibleWork($ledger,array('mode'=>'auto','batch_size'=>25,'excluded_earning_ids'=>array(10),'excluded_block_ids'=>array(29244)));
live_expect($excluded['selected_earning_ids']===array()&&strpos($g->sql,'E.id NOT IN (:excluded_earning_0)')!==false&&strpos($g->sql,'B.id NOT IN (:excluded_block_0)')!==false,'durable earning/block exclusions were not applied before the live selection limit',$fail);
live_expect($g->params[':excluded_earning_0']===10&&$g->params[':excluded_block_0']===29244&&$excluded['durable_queue_exclusions']===array('earning_ids'=>array(10),'block_ids'=>array(29244)),'durable queue exclusion evidence was not reported exactly',$fail);
$bad=array();$pre=live_row(1,29242);$bad[]=$pre;for($i=0;$i<75;$i++)$bad[]=live_row(13126+$i,17995+$i);
$mutations=array(array('candidate',false),array('candidate_coin_id',1268),array('candidate_algo','sha256'),array('candidate_hash','wrong'),array('category','immature'),array('category','orphan'),array('status',0),array('status',-1),array('status',2),array('coin_id',1268),array('account_coinid',1268));foreach($mutations as $n=>$m){$x=live_row(200+$n,29300+$n);$x[$m[0]]=$m[1];$bad[]=$x;}
$g->rows=$bad;$r=$a->selectEligibleWork($ledger,array('mode'=>'auto','batch_size'=>25));live_expect($r['selected_earning_ids']===array(),'pre-boundary, parked, orphan, or malformed lineage entered live scope',$fail);
$groestl=(new BadpoolLivePaymentLaneRegistry())->get('live-groestl-v1');$gg=new GroestlSelectionGuard();for($i=0;$i<30;$i++)$gg->rows[]=groestl_row(1000+$i,31213+$i);$gg->rows[]=groestl_row(999,31212);$gg->rows[]=live_row(998,31300);$badMature=groestl_row(997,31301);$badMature['mature_time']=null;$gg->rows[]=$badMature;$badAlgo=groestl_row(996,31302);$badAlgo['candidate_algo']='scrypt';$gg->rows[]=$badAlgo;
$gledger=array('mode'=>'auto','run_directory'=>$root,'selected_coin_scope'=>array(array('id'=>1269)));$ga=new BadpoolPaymentBatchPhaseAdapter($gg,function(){});$gr=$ga->selectEligibleWork($gledger,array('mode'=>'auto','batch_size'=>25,'lane_configuration'=>$groestl));
live_expect($gr['selected_earning_ids']===range(1000,1024),'Groestl selection was not bounded to the first 25 exact status-1 rows',$fail);
live_expect($gg->params===array(':coin'=>1269,':algo'=>'badcoin-groestl',':boundary'=>31212),'Groestl selector parameters escaped the ownership envelope',$fail);
$greport=json_decode(file_get_contents($gr['report_path']),true);live_expect($greport[0]['scope']===array('coin_id'=>1269,'algo'=>'badcoin-groestl','block_id_gt'=>31212,'earning_status'=>1,'block_category'=>'generate'),'Groestl selection report scope is incomplete',$fail);
$g->rows=array(groestl_row(2000,31303));$cross=$a->selectEligibleWork($ledger,array('mode'=>'auto','batch_size'=>25));live_expect($cross['selected_earning_ids']===array(),'Groestl earning entered Scrypt selection',$fail);
$delayLedger=$ledger+array('selected_earning_ids'=>array(10,20),'selected_work_by_coin'=>array('1267'=>array('earning_ids'=>array(10,20))));
foreach(array('exact'=>array(10,20),'subset'=>array(10),'superset'=>array(9,10,20),'malformed'=>array('x',20),'duplicate'=>array(10,10,20)) as $case=>$ids){$e=new LiveDelayExecutor();$e->returned=$ids;$adapter=new BadpoolPaymentBatchPhaseAdapter($g,array($e,'run'));$x=$adapter->paymentDelayCheck($delayLedger,array());$pass=$case==='exact';live_expect(($x['status']==='pass')===$pass,'payment delay '.$case.' did not fail closed',$fail);live_expect(in_array('--selected-earning-ids=10,20',$e->calls[0][1],true),'payment delay command omitted exact IDs',$fail);if($pass)live_expect($x['payment_delay_qualified_earning_ids']===array(10,20),'qualified IDs were not durably returned',$fail);}
$empty=$delayLedger;$empty['selected_earning_ids']=array();$empty['selected_work_by_coin']['1267']['earning_ids']=array();$e=new LiveDelayExecutor();$x=(new BadpoolPaymentBatchPhaseAdapter($g,array($e,'run')))->paymentDelayCheck($empty,array());live_expect($x['status']==='pass'&&$x['payment_delay_qualified_earning_ids']===array()&&$e->calls===array(),'empty delay scope was not explicit/no-query',$fail);
foreach(scandir($root) as $f)if($f!=='.'&&$f!=='..')unlink($root.'/'.$f);rmdir($root);
if($fail){echo "Badpool live status1 payment selection harness FAILED\n - ".implode("\n - ",$fail)."\n";exit(1);}echo "Badpool live status1 payment selection harness passed\n";
