<?php
$root = dirname(__DIR__);
$commandPath = $root.'/web/yaamp/commands/BadpoolGuardCommand.php';
$docPath = $root.'/docs/badpool-stage1-drain-runner.md';
$failures = array();
function expect_contains($label,$haystack,$needle,&$failures){ if(strpos($haystack,$needle)===false) $failures[]="$label: missing expected text: $needle"; }
function expect_not_contains($label,$haystack,$needle,&$failures){ if(strpos($haystack,$needle)!==false) $failures[]="$label: found forbidden text: $needle"; }
function section_between($haystack,$start,$end){ $s=strpos($haystack,$start); if($s===false)return ''; $e=strpos($haystack,$end,$s+strlen($start)); if($e===false)$e=strlen($haystack); return substr($haystack,$s,$e-$s); }
$command = is_file($commandPath) ? file_get_contents($commandPath) : '';
$doc = is_file($docPath) ? file_get_contents($docPath) : '';
if($command==='') $failures[]='Missing command file';
if($doc==='') $failures[]='Missing drain runner doc';
$plan = section_between($command, 'private function forwardCatchupStage1DrainPlanReport', 'private function forwardCatchupStage1DrainApplyReport');
$apply = section_between($command, 'private function forwardCatchupStage1DrainApplyReport', 'private function forwardCatchupStage1DrainContextArgs');
$validate = section_between($command, 'private function forwardCatchupStage1DrainValidate', 'private function forwardCatchupStage1DrainBaseReport');
$base = section_between($command, 'private function forwardCatchupStage1DrainBaseReport', 'private function forwardCatchupStage1DrainBatchSummary');
$fail = section_between($command, 'private function forwardCatchupStage1DrainFail', 'private function earningsMaturityTransitionDryrunReport');
expect_contains('plan action registered', $command, "'forward-catchup-stage1-drain-plan'", $failures);
expect_contains('apply action registered', $command, "'forward-catchup-stage1-drain-apply'", $failures);
expect_contains('safe max batches constant', $command, 'FORWARD_CATCHUP_STAGE1_DRAIN_SAFE_MAX_BATCHES = 10', $failures);
expect_contains('confirmation token constant', $command, "FORWARD_CATCHUP_STAGE1_DRAIN_CONFIRMATION = 'stage1_only_no_later_accounting_no_wallet'", $failures);
expect_contains('plan is read-only', $plan, "forwardCatchupStage1DrainBaseReport('forward-catchup-stage1-drain-plan', true", $failures);
expect_not_contains('plan must not call mutation helper', $plan, 'forwardCatchupStage1ApplyMutations', $failures);
expect_not_contains('plan must not open transaction', $plan, 'beginTransaction', $failures);
expect_contains('apply requires operator confirmation', $validate, 'operator-confirms-stage1-drain', $failures);
expect_contains('apply exact confirmation', $validate, 'self::FORWARD_CATCHUP_STAGE1_DRAIN_CONFIRMATION', $failures);
expect_contains('missing coin id refused', $validate, 'coin_id_required', $failures);
expect_contains('batch limit max 50 refused', $validate, 'limit_gt_50', $failures);
expect_contains('missing max batches refused', $validate, 'max-batches', $failures);
expect_contains('safe cap enforced', $validate, 'max_batches_safe_cap_exceeded', $failures);
expect_contains('preview/apply schema split', $base, "\$report['schema'] = \$readOnly ? 'badpool.guardrail.preview.v1' : self::APPLY_SCHEMA;", $failures);
expect_contains('preview/apply mode split', $base, "\$report['mode'] = \$readOnly ? 'read-only-preview' : self::APPLY_MODE;", $failures);
expect_contains('apply commands initially false', $base, "\$report['apply_commands_executed'] = false;", $failures);
expect_contains('projected earnings total', $base, 'total_projected_earnings', $failures);
foreach(array('account_credit','payout_rows_created','wallet_sends','backend_loops_run','shares_deleted') as $flag) expect_contains('blocked flag '.$flag, $base, "\$report['$flag'] = false", $failures);
expect_contains('per batch checksums', $command, 'projected_mutation_checksum', $failures);
expect_contains('per batch projected earnings rows', $command, 'projected_earnings_rows', $failures);
expect_contains('per batch inserted earnings count', $command, 'inserted_earnings_count', $failures);
expect_contains('per batch reconciliation', $apply, "\$report['per_batch'][\$currentBatchIndex]['reconciliation_status']", $failures);
expect_contains('attempt recorded before approval regeneration', $apply, "\$report['failure_phase'] = 'approval_regeneration';", $failures);
expect_contains('preflight failure phase', $apply, "\$report['failure_phase'] = 'preflight_validation';", $failures);
expect_contains('mutation failure phase', $apply, "\$report['failure_phase'] = 'mutation_execution';", $failures);
expect_contains('verification failure phase', $apply, "\$report['failure_phase'] = 'post_apply_verification';", $failures);
expect_contains('commit recorded immediately', $apply, "\$tx->commit();\n\t\t\t\t// Record the commit", $failures);
expect_contains('committed count incremented', $apply, "\$report['committed_batches']++;", $failures);
expect_contains('commit sets mutation boolean', $apply, "\$report['db_mutations'] = true;", $failures);
expect_contains('rollback is confirmed', $apply, "\$report['failing_transaction_rolled_back'] = true;", $failures);
expect_contains('selected scope retained in batch', $command, "'selected_scope'=>\$selectedScope", $failures);
expect_contains('committed batch retained before verification', $apply, "\$report['per_batch'][] = \$batch;", $failures);
expect_contains('committed batch flag', $apply, "\$batch['committed'] = true;", $failures);
expect_contains('verification failure phase retained per batch', $apply, "\$batch['failure_phase'] = 'post_apply_verification';", $failures);
expect_contains('verification false retained before verification', $apply, "\$batch['verification_passed'] = false;", $failures);
expect_contains('manual verification retained before verification', $apply, "\$batch['manual_verification_required'] = true;", $failures);
expect_contains('successful verification updates retained batch', $apply, "\$report['per_batch'][\$currentBatchIndex]['verification_passed'] = true;", $failures);
expect_contains('apply command flag set immediately before mutation', $apply, "\$report['apply_commands_executed'] = true;\n\t\t\t\t\$applied = \$this->forwardCatchupStage1ApplyMutations", $failures);
expect_contains('stops preview empty', $apply, "\$report['stop_reason'] = 'preview_empty'; break;", $failures);
expect_contains('stops selected mismatch', $apply, 'selected_count_mismatch', $failures);
expect_contains('stops approval refusal', $apply, 'approval_package_refusal', $failures);
expect_contains('stops apply refusal', $apply, 'apply_refusal', $failures);
expect_contains('stops post verification failure', $apply, 'post_apply_verification_failure', $failures);
expect_contains('summary totals helper', $command, 'private function forwardCatchupStage1DrainAddTotals', $failures);
expect_contains('base committed count', $base, "'committed_batches'", $failures);
expect_contains('post-commit failure is hold', $fail, "\$report['status'] = \$committed ? 'hold' : 'refused';", $failures);
expect_contains('post-commit manual verification', $fail, "\$report['manual_verification_required'] = \$committed;", $failures);
expect_contains('post-commit manual reconciliation', $fail, "\$report['manual_reconciliation_required'] = \$committed;", $failures);
expect_contains('explicit prior commit state', $fail, "\$report['prior_commit_state'] = \$committed ? 'committed' : 'none';", $failures);
expect_contains('post-commit warning', $fail, 'manually verify/reconcile database state', $failures);
expect_contains('totals selected from per batch', $command, "\$report['total_selected'] += intval(\$batch['selected_count']);", $failures);
expect_contains('totals projected earnings from per batch', $command, "\$report['total_projected_earnings'] += intval(arraySafeVal(\$batch, 'projected_earnings_rows'", $failures);
expect_contains('totals inserted earnings default zero', $command, "\$report['total_inserted_earnings'] += intval(arraySafeVal(\$batch, 'inserted_earnings_count', 0));", $failures);
expect_contains('docs plan shape', $doc, 'forward-catchup-stage1-drain-plan', $failures);
expect_contains('docs apply shape', $doc, 'forward-catchup-stage1-drain-apply', $failures);
expect_contains('docs plan inserted zero', $doc, 'plan output keeps total_inserted_earnings at 0', $failures);
expect_contains('docs apply commands flag', $doc, 'apply_commands_executed', $failures);
expect_contains('docs hard boundary', $doc, 'no maturity transition', $failures);
foreach(array('BackendPayments','BackendCoinPayments','PayoutCommand','badpoolGuardedSendmanyApply','DELETE FROM shares','startService(','restartService(') as $bad) expect_not_contains('unsafe broad path in drain apply', $apply, $bad, $failures);
if($failures){ echo "Badpool Stage1 drain guard harness FAILED\n"; foreach($failures as $f) echo " - $f\n"; exit(1); }
echo "Badpool Stage1 drain guard harness passed\n";
