<?php
require_once(dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolYiiExactMultiWalletPayoutRepository.php');
$checks=0;$failures=array();function pr_ok($v,$m){global$checks,$failures;$checks++;if(!$v)$failures[]=$m;}function pr_throws($f){try{$f();return false;}catch(Exception$e){return true;}}
class RepoFixtureCommand{private$db,$sql;function __construct($db,$sql){$this->db=$db;$this->sql=$sql;}function queryAll($assoc,$params){$this->db->selectSql[]=$this->sql;$ids=array_map('intval',array_values($params));$out=array();foreach($this->db->rows as$id=>$r)if(in_array($id,$ids,true))$out[]=$r;usort($out,function($a,$b){return$a['payout_id']-$b['payout_id'];});return$out;}function execute($p){$id=intval($p[':id']);if($this->db->failUpdateId===$id)return 0;$r=&$this->db->rows[$id];if(!$r||$r['account_id']!==$p[':account_id']||$r['coin_id']!==$p[':coin_id']||$r['amount']!==$p[':amount']||$r['completed']!==0||$r['tx']!==null)return 0;$r['completed']=1;$r['tx']=$p[':txid'];return 1;}}
class RepoFixtureTransaction{private$db,$snapshot;function __construct($db){$this->db=$db;$this->snapshot=$db->rows;}function commit(){$this->db->commits++;}function rollback(){$this->db->rows=$this->snapshot;$this->db->rollbacks++;}}
class RepoFixtureDb{public$rows=array(),$selectSql=array(),$failUpdateId=null,$commits=0,$rollbacks=0;function createCommand($sql){return new RepoFixtureCommand($this,$sql);}function beginTransaction(){return new RepoFixtureTransaction($this);}}
function pr_state($root,$lane,$batch){$s=array('schema'=>$lane->get('ownership_schema'),'version'=>1,'lane'=>$lane->laneId(),'coin_id'=>$lane->coinId(),'algo'=>$lane->dbAlgo(),'block_id_gt'=>$lane->blockBoundary(),'active_batch_id'=>$batch,'last_observed_batch_state'=>'READY_FOR_WALLET_APPROVAL');file_put_contents($lane->statePath($root),json_encode($s));}
function pr_ledger($root,$lane,$batch,$ids){mkdir($root.'/'.$batch);$l=array('batch_id'=>$batch,'batch_state'=>'READY_FOR_WALLET_APPROVAL','coordinator_owner'=>$lane->ownershipEnvelope(),'created_payout_ids'=>$ids);file_put_contents($root.'/'.$batch.'/ledger.json',json_encode($l));}
function pr_clean($p){if(!is_dir($p))return;foreach(scandir($p)as$f)if($f!=='.'&&$f!=='..'){$c=$p.'/'.$f;if(is_dir($c))pr_clean($c);else unlink($c);}rmdir($p);}
$root=sys_get_temp_dir().'/badpool-production-repo-'.bin2hex(random_bytes(5));mkdir($root);$registry=new BadpoolLivePaymentLaneRegistry();
$lanes=array(526=>$registry->get('live-scrypt-v1'),527=>$registry->get('live-groestl-v1'),528=>$registry->get('live-yescrypt-v1'));
foreach($lanes as$id=>$lane){$batch='batch-'.$id;pr_state($root,$lane,$batch);pr_ledger($root,$lane,$batch,array($id));}
$db=new RepoFixtureDb();foreach(array(526=>array(79,1267,'54111.530811649995','BAD-scrypt-account-79'),527=>array(76,1269,'55875.65007076999','BAD-groestl-account-76'),528=>array(75,1266,'33063.28546626001','BAD-yescrypt-account-75'),529=>array(90,1267,'1.00000001','BAD-unapproved-account-90'))as$id=>$v)$db->rows[$id]=array('payout_id'=>$id,'account_id'=>$v[0],'coin_id'=>$v[1],'amount'=>$v[2],'completed'=>0,'tx'=>null,'recipient'=>$v[3],'account_coin_id'=>$v[1],'joined_coin_id'=>$v[1]);
$repo=new BadpoolYiiExactMultiWalletPayoutRepository($db,$root,$registry);$rows=$repo->loadExactPayouts(array(526,527,528));
pr_ok(array_column($rows,'payout_id')===array(526,527,528),'exact fixture IDs resolved');pr_ok(count($rows)===3,'no broad payout sweep');pr_ok(strpos($db->selectSql[0],'WHERE P.id IN')!==false,'query authority is explicit IDs');pr_ok(!in_array(529,array_column($rows,'payout_id'),true),'unrelated payout excluded');
pr_ok($rows[0]['recipient']==='BAD-scrypt-account-79'&&$rows[1]['recipient']==='BAD-groestl-account-76'&&$rows[2]['recipient']==='BAD-yescrypt-account-75','recipients sourced from joined account fixture');pr_ok($rows[0]['lane_id']==='live-scrypt-v1'&&$rows[1]['lane_id']==='live-groestl-v1'&&$rows[2]['lane_id']==='live-yescrypt-v1','lane ownership proven');pr_ok($rows[0]['batch_state']==='READY_FOR_WALLET_APPROVAL'&&$rows[1]['batch_state']==='READY_FOR_WALLET_APPROVAL','batch state proven');
pr_ok(pr_throws(function()use($repo){$repo->loadExactPayouts(array(526,526));}),'duplicate payout refused');pr_ok(pr_throws(function()use($repo){$repo->loadExactPayouts(array(999));}),'unknown payout refused');
$state=$lanes[527]->statePath($root);$saved=file_get_contents($state);unlink($state);pr_ok(pr_throws(function()use($repo){$repo->loadExactPayouts(array(527));}),'missing active ownership refused');file_put_contents($state,$saved);
$ledger=$root.'/batch-528/ledger.json';$savedLedger=file_get_contents($ledger);$bad=json_decode($savedLedger,true);$bad['batch_state']='WAITING_PAYMENT_DELAY';file_put_contents($ledger,json_encode($bad));pr_ok(pr_throws(function()use($repo){$repo->loadExactPayouts(array(528));}),'non-ready ledger refused');file_put_contents($ledger,$savedLedger);
$approved=$repo->loadExactPayouts(array(526,527,528));$map=array(526=>str_repeat('a',64),527=>str_repeat('b',64),528=>str_repeat('c',64));$count=$repo->reconcileExactWithTransactionIds($approved,$map);pr_ok($count===3&&$db->commits===1,'exact reconciliation committed once');pr_ok($db->rows[526]['tx']===$map[526]&&$db->rows[527]['tx']===$map[527]&&$db->rows[528]['tx']===$map[528],'wallet-specific txids persisted');pr_ok($db->rows[529]['completed']===0&&$db->rows[529]['tx']===null,'unrelated incomplete payout untouched');
foreach(array(526,527,528)as$id){$db->rows[$id]['completed']=0;$db->rows[$id]['tx']=null;}$db->failUpdateId=527;pr_ok(pr_throws(function()use($repo,$approved,$map){$repo->reconcileExactWithTransactionIds($approved,$map); }),'reconciliation failure reported');pr_ok($db->rollbacks===1&&$db->rows[526]['completed']===0&&$db->rows[527]['completed']===0&&$db->rows[528]['completed']===0,'reconciliation rollback all-or-none');
pr_clean($root);if($failures){echo"FAIL multi-wallet production repository harness ($checks checks)\n - ".implode("\n - ",$failures)."\n";exit(1);}echo"PASS multi-wallet production repository harness ($checks checks)\n";
