<?php
require_once(dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolLivePaymentCoordinator.php');
$fail=0; function okc($v,$m){global $fail;if(!$v){echo "FAIL: $m\n";$fail++;}}
class CoordinatorRunnerFixture {
	public $root,$state,$calls=0,$selection=array(15620,15621);
	function __construct($r,$s='WAITING_PAYMENT_DELAY'){$this->root=$r;$this->state=$s;}
	function run($o){$this->calls++;$id=isset($o['resume_batch_id'])?$o['resume_batch_id']:'20260918T010000Z-aaaaaaaaaaaa';$p=$this->root.'/'.$id;if(!is_dir($p))mkdir($p,0770,true);$old=is_file($p.'/ledger.json')?json_decode(file_get_contents($p.'/ledger.json'),true):null;
		$l=$old?:array('batch_id'=>$id,'mode'=>'auto','scope'=>'all-active-payout-coins','only'=>'scrypt','batch_size'=>25,'stop_before_wallet_send'=>true,'coordinator_owner'=>$o['coordinator_owner'],'selected_coin_scope'=>array(array('id'=>1267,'algo'=>'scrypt')),'selected_earning_ids'=>$this->selection,'selected_block_ids'=>$this->selection?array(29243,29244):array(),'selected_account_ids'=>$this->selection?array(79):array(),'created_payout_ids'=>array(),'current_phase'=>4,'batch_state'=>$this->state);
		file_put_contents($p.'/ledger.json',json_encode($l));if(!$this->selection)file_put_contents($p.'/phase-artifact.json','{}');return array('batch_id'=>$id);
	}
}
function rootc(){ $r=sys_get_temp_dir().'/badpool-coordinator-'.bin2hex(random_bytes(5));mkdir($r);return $r; }
function statec($r,$id){$lane=BadpoolLivePaymentLaneRegistry::scryptCompatibility();file_put_contents($lane->statePath($r),json_encode(array('schema'=>$lane->get('ownership_schema'),'version'=>1,'lane'=>$lane->laneId(),'coin_id'=>$lane->coinId(),'algo'=>$lane->dbAlgo(),'block_id_gt'=>$lane->blockBoundary(),'active_batch_id'=>$id)));}
function ledgerc($r,$id,$changes=array()){$lane=BadpoolLivePaymentLaneRegistry::scryptCompatibility();$base=array('batch_id'=>$id,'mode'=>'auto','only'=>$lane->operationalAlgo(),'batch_size'=>$lane->batchLimit(),'stop_before_wallet_send'=>true,'coordinator_owner'=>$lane->ownershipEnvelope(),'selected_coin_scope'=>array(array('id'=>$lane->coinId(),'algo'=>$lane->dbAlgo())),'selected_earning_ids'=>array(1,2),'selected_block_ids'=>array(29243,29244),'selected_account_ids'=>array(79),'created_payout_ids'=>array(),'current_phase'=>4,'batch_state'=>'WAITING_PAYMENT_DELAY');$l=array_merge($base,$changes);mkdir($r.'/'.$id);file_put_contents($r.'/'.$id.'/ledger.json',json_encode($l));return $l;}
$r=rootc();$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===1&&$x['active_batch_id']!==null&&$x['action_taken']==='created_batch','creates one bounded batch');$l=json_decode(file_get_contents($r.'/'.$x['active_batch_id'].'/ledger.json'),true);okc($l['batch_size']===25&&$l['coordinator_owner']['lane']==='live-scrypt-v1','bound and ownership metadata');
$r=rootc();$f=new CoordinatorRunnerFixture($r);$f->selection=array();$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($x['classification']==='IDLE'&&$x['active_batch_id']===null&&count(glob($r.'/*/ledger.json'))===0,'empty work is idle without artifact');
$r=rootc();$f=new CoordinatorRunnerFixture($r);$f->selection=array();for($n=0;$n<100;$n++)(new BadpoolLivePaymentCoordinator($f,$r))->run();$dirs=array_filter(glob($r.'/*'), 'is_dir');okc(count($dirs)===0,'100 empty runs leave no batch artifact directories');
$r=rootc();$id='20260918T010001Z-bbbbbbbbbbbb';ledgerc($r,$id);statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===1&&$x['active_batch_id']===$id&&$x['action_taken']==='resumed_batch','waiting resumes exact batch');$l=json_decode(file_get_contents($r.'/'.$id.'/ledger.json'),true);okc($l['selected_earning_ids']===array(1,2),'resume scope immutable');
$r=rootc();$id='20260918T010002Z-cccccccccccc';ledgerc($r,$id,array('batch_state'=>'READY_FOR_WALLET_APPROVAL','current_phase'=>6,'created_payout_ids'=>array(900)));statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===0&&$x['classification']==='HUMAN_WALLET_APPROVAL_REQUIRED'&&$x['human_action_required']&&$x['created_payout_ids']===array(900),'wallet boundary holds and reports payout');
$r=rootc();$fixture=dirname(__FILE__).'/fixtures/badpool_live_scrypt_parked_state_v1.json';copy($fixture,$r.'/live-scrypt-coordinator.json');$id='20260920T120829Z-414141f5f7d0';ledgerc($r,$id,array('batch_state'=>'READY_FOR_WALLET_APPROVAL','current_phase'=>6,'created_payout_ids'=>array(526)));$before=hash_file('sha256',$r.'/'.$id.'/ledger.json');$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();$parked=json_decode(file_get_contents($r.'/live-scrypt-coordinator.json'),true);okc($f->calls===0&&$x['classification']==='HUMAN_WALLET_APPROVAL_REQUIRED'&&$x['active_batch_id']===$id&&$x['created_payout_ids']===array(526),'parked production batch/payout fixture changed identity');okc($x['current_phase']===6&&$x['batch_state']==='READY_FOR_WALLET_APPROVAL'&&$x['human_action_required']===true,'parked production approval boundary changed');okc(hash_file('sha256',$r.'/'.$id.'/ledger.json')===$before&&$parked['schema']==='badpool.live_payment_coordinator.v1'&&$parked['version']===1,'parked ledger was mutated or state required migration');okc($x['wallet_rpc_used']===false&&$x['wallet_send_performed']===false&&$x['db_mutations_by_coordinator']===false,'observing parked fixture reached mutation or wallet work');
$r=rootc();$id='20260918T010003Z-dddddddddddd';ledgerc($r,$id,array('batch_state'=>'HOLD_COMPLETED_PAYOUT_RECONCILIATION','current_phase'=>6,'created_payout_ids'=>array(901)));statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===0&&$x['classification']==='COMPLETED_PAYOUT_RECONCILIATION_REQUIRED'&&$x['next_safe_action']==='read_only_wallet_proof_closeout','completed payout blocks resend');
$r=rootc();$id='20260918T010007Z-222222222222';ledgerc($r,$id,array('batch_state'=>'RECONCILED','current_phase'=>6,'created_payout_ids'=>array(902)));statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();$state=json_decode(file_get_contents($r.'/live-scrypt-coordinator.json'),true);okc($x['classification']==='READY_FOR_NEW_BATCH'&&$x['active_batch_id']===null&&$f->calls===0,'reconciled active ledger releases state without immediate creation');okc($state['last_terminal_reconciled_batch_id']===$id,'terminal batch ID recorded');$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===1&&$x['action_taken']==='created_batch','next invocation permits bounded batch');
foreach(array('HOLD','FAIL','REFUSED','MYSTERY') as $s){$r=rootc();$id='20260918T010004Z-eeeeeeeeeeee';ledgerc($r,$id,array('batch_state'=>$s));statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($x['classification']==='FAIL_CLOSED'&&$f->calls===0,"$s fails closed");}
$bad=array('mode'=>'normal','only'=>'sha256d','batch_size'=>26,'stop_before_wallet_send'=>false,'selected_earning_ids'=>array(1,1),'selected_block_ids'=>array(2,2),'selected_account_ids'=>array(0),'selected_coin_scope'=>array(array('id'=>1,'algo'=>'scrypt')));
foreach($bad as $k=>$v){$r=rootc();$id='20260918T010005Z-ffffffffffff';ledgerc($r,$id,array($k=>$v));statec($r,$id);$x=(new BadpoolLivePaymentCoordinator(new CoordinatorRunnerFixture($r),$r))->run();okc($x['classification']==='FAIL_CLOSED',"invalid $k fails closed");}
foreach(array('lane'=>'other-lane','coin_id'=>1268,'algo'=>'yescrypt','block_id_gt'=>1) as $k=>$v){$r=rootc();$id='20260918T010008Z-333333333333';$owner=BadpoolLivePaymentLaneRegistry::scryptCompatibility()->ownershipEnvelope();$owner[$k]=$v;ledgerc($r,$id,array('coordinator_owner'=>$owner));statec($r,$id);$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($x['classification']==='FAIL_CLOSED'&&$f->calls===0,"owner $k mismatch fails closed");}
$r=rootc();$id='20260918T010009Z-444444444444';ledgerc($r,$id);statec($r,$id);$state=json_decode(file_get_contents($r.'/live-scrypt-coordinator.json'),true);$state['algo']='yescrypt';file_put_contents($r.'/live-scrypt-coordinator.json',json_encode($state));$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($x['classification']==='FAIL_CLOSED'&&$f->calls===0,'state identity mismatch fails closed');
$r=rootc();$id='20260918T010006Z-111111111111';statec($r,$id);$x=(new BadpoolLivePaymentCoordinator(new CoordinatorRunnerFixture($r),$r))->run();okc($x['classification']==='FAIL_CLOSED','missing ledger fails closed');
$r=rootc();mkdir($r.'/20260918T005930Z-8089f25db0fe');file_put_contents($r.'/20260918T005930Z-8089f25db0fe/ledger.json','{}');$f=new CoordinatorRunnerFixture($r);$x=(new BadpoolLivePaymentCoordinator($f,$r))->run();okc($f->calls===1,'canary/unowned artifacts are not adopted');
okc($x['db_mutations_by_coordinator']===false&&$x['wallet_rpc_used']===false&&$x['wallet_send_performed']===false,'no direct mutation or wallet reachability');
echo $fail?"$fail coordinator checks failed\n":"badpool live payment coordinator harness passed\n";exit($fail?1:0);
