<?php
require_once dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolLiveBlockEnrichmentBridge.php';
$fail=array();function ee($v,$m){global $fail;if(!$v)$fail[]=$m;}
class EnrichRpc {public $block,$tx,$down=false;function getblock($h){if($this->down)return false;return $this->block;}function gettransaction($h){if($this->down)return false;return $this->tx;}}
class EnrichStore implements BadpoolLiveBlockEnrichmentStore {
 public $rows=array(),$blocks=array(),$other=array('earnings'=>1,'accounts'=>2,'shares'=>3,'payouts'=>4,'wallets'=>5,'attributions'=>6),$fail=false;
 function candidates($coin,$algo,$ids,$limit){$out=array();foreach($this->rows as $r)if($r['candidate_coin_id']==$coin&&$r['candidate_algo']===$algo&&(!$ids||in_array($r['block_id'],$ids,true)))$out[]=$r;usort($out,function($a,$b){return $a['block_id']-$b['block_id'];});return array_slice($out,0,$limit);}
 function applyEnrichments($updates){$before=$this->blocks;try{foreach($updates as $u){$id=$u['block_id'];if(BadpoolLiveBlockEnrichmentBridge::checksum($this->blocks[$id])!==BadpoolLiveBlockEnrichmentBridge::checksum($u['expected_block']))throw new RuntimeException('locked drift');$this->blocks[$id]=array_merge($this->blocks[$id],$u['enrichment']);if($this->fail)throw new RuntimeException('forced rollback');}return array('updated_count'=>count($updates),'reconciled_count'=>count($updates));}catch(Exception $e){$this->blocks=$before;throw $e;}}
}
function erow($id){return array('block_id'=>$id,'candidate_coin_id'=>1267,'candidate_algo'=>'scrypt','candidate_blockhash'=>'hash'.$id,'block_exists'=>true,'block_coin_id'=>1267,'block_algo'=>'scrypt','block_blockhash'=>'hash'.$id,'block_txhash'=>null,'block_amount'=>null,'block_confirmations'=>null,'block_price'=>null,'block_category'=>'new','coin_price'=>'.01','coin'=>(object)array('id'=>1267));}
function estate($r){return array('id'=>$r['block_id'],'coin_id'=>$r['block_coin_id'],'blockhash'=>$r['block_blockhash'],'txhash'=>$r['block_txhash'],'amount'=>$r['block_amount'],'confirmations'=>$r['block_confirmations'],'price'=>$r['block_price'],'category'=>$r['block_category']);}
$s=new EnrichStore;$s->rows=array(erow(2),erow(1));foreach($s->rows as $r)$s->blocks[$r['block_id']]=estate($r);$rpc=new EnrichRpc;$rpc->block=array('hash'=>'hash1','tx'=>array('tx1'),'confirmations'=>3);$rpc->tx=array('confirmations'=>3,'details'=>array(array('category'=>'immature','amount'=>8)));
$b=new BadpoolLiveBlockEnrichmentBridge($s,function($coin)use($rpc){return $rpc;});
$r=$b->dryrun(1267,'scrypt',array(1));ee($r['approved_count']===1&&$r['inventory'][0]['enrichment']['amount']==='8.000000000000','daemon enrichment success');
$all=$b->dryrun(1267,'scrypt',array(),1);ee($all['selected_block_ids']===array(1),'deterministic ordering and limit');
$unknown=$b->dryrun(1267,'scrypt',array(99));ee($unknown['blocked_count']===1&&$unknown['inventory'][0]['blocked_reasons']===array('unknown_or_non_live_block_id'),'live-candidate-only selection');
try{BadpoolLiveBlockEnrichmentBridge::parseIds('1,1');ee(false,'duplicate accepted');}catch(Exception $e){}try{$b->dryrun(1267,'sha256',array(1));ee($b->dryrun(1267,'sha256',array(1))['blocked_count']===1,'algo mismatch refused');}catch(Exception $e){}
$missing=erow(3);$missing['block_exists']=false;$s->rows[]=$missing;$m=$b->dryrun(1267,'scrypt',array(3));ee(in_array('missing_block',$m['inventory'][0]['blocked_reasons'],true),'missing block');
$rpc->down=true;$down=$b->dryrun(1267,'scrypt',array(1));ee(in_array('blocked_pending_rpc',$down['inventory'][0]['blocked_reasons'],true),'unavailable RPC');$rpc->down=false;
$rpc->block=array('hash'=>'hash1','tx'=>array('tx1'),'confirmations'=>2);$rpc->tx=array('confirmations'=>2,'details'=>'bad');$bad=$b->dryrun(1267,'scrypt',array(1));ee(in_array('blocked_invalid_rpc_result',$bad['inventory'][0]['blocked_reasons'],true),'malformed transaction');
$rpc->tx=array('confirmations'=>2,'details'=>array(array('category'=>'immature','amount'=>null)));$null=$b->dryrun(1267,'scrypt',array(1));ee(in_array('blocked_pending_block_amount',$null['inventory'][0]['blocked_reasons'],true),'NULL amount refusal');
$rpc->block=array('hash'=>'hash1','tx'=>array('tx1'),'confirmations'=>-1);$orphan=$b->dryrun(1267,'scrypt',array(1));ee($orphan['inventory'][0]['enrichment']['category']==='orphan'&&$orphan['inventory'][0]['enrichment']['amount']==='0.000000000000','explicit orphan classification');
$rpc->block=array('hash'=>'hash1','tx'=>array('tx1'),'confirmations'=>3);$rpc->tx=array('confirmations'=>3,'details'=>array(array('category'=>'generate','amount'=>8)));$p=$b->approvalPackage(1267,'scrypt',array(1));$p2=$b->approvalPackage(1267,'scrypt',array(1));ee($p['approval_package_checksum']===$p2['approval_package_checksum'],'package checksum stability');$provided=array();foreach(array('candidate_inventory_checksum','block_inventory_checksum','rpc_result_checksum','selected_scope_checksum') as $k)$provided[$k]=$p[$k];
$other=$s->other;$ap=$b->applyPackage($p,$provided,BadpoolLiveBlockEnrichmentBridge::CONFIRMATION);ee($ap['updated_count']===1&&$s->blocks[1]['category']==='generate','approved apply');ee($s->other===$other,'financial and attribution tables untouched');
$s2=new EnrichStore;$x=erow(7);$s2->rows=array($x);$s2->blocks[7]=estate($x);$r2=new EnrichRpc;$r2->block=array('hash'=>'hash7','tx'=>array('t'),'confirmations'=>1);$r2->tx=array('confirmations'=>1,'details'=>array(array('amount'=>4,'category'=>'immature')));$b2=new BadpoolLiveBlockEnrichmentBridge($s2,function($c)use($r2){return $r2;});$q=$b2->approvalPackage(1267,'scrypt',array(7));$pv=array();foreach(array('candidate_inventory_checksum','block_inventory_checksum','rpc_result_checksum','selected_scope_checksum')as$k)$pv[$k]=$q[$k];$s2->rows[0]['candidate_blockhash']='changed';try{$b2->applyPackage($q,$pv,BadpoolLiveBlockEnrichmentBridge::CONFIRMATION);ee(false,'candidate drift accepted');}catch(Exception $e){}$s2->rows[0]=$x;$s2->rows[0]['block_category']='immature';try{$b2->applyPackage($q,$pv,BadpoolLiveBlockEnrichmentBridge::CONFIRMATION);ee(false,'block drift accepted');}catch(Exception $e){}
$s2->rows[0]=$x;$s2->blocks[7]=estate($x);$s2->fail=true;try{$b2->applyPackage($q,$pv,BadpoolLiveBlockEnrichmentBridge::CONFIRMATION);}catch(Exception $e){}ee($s2->blocks[7]===estate($x),'transactional rollback');
$src=file_get_contents(dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolLiveBlockEnrichmentBridge.php');ee(strpos($src,"category='new'")===false&&strpos($src,'category = \'new\'')===false,'no historical new fallback');foreach(array('BackendBlockNew(','BackendBlocksUpdate(','BackendBlockFind1(','BackendBlockFind2(')as$f)ee(strpos($src,$f)===false,$f.' not called');foreach(array('earnings','accounts','shares','payouts','wallets','live_block_attributions')as$t)ee(stripos($src,'UPDATE '.$t)===false&&stripos($src,'INSERT INTO '.$t)===false,$t.' untouched');
if($fail)throw new RuntimeException('FAIL: '.implode('; ',$fail));echo "PASS live capture block enrichment harness\n";
