<?php
function arraySafeVal($a,$k,$d=null){return isset($a[$k])?$a[$k]:$d;}
require_once dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolLiveCaptureEarningsBridge.php';
$fail=array(); function ok($v,$m){global $fail;if(!$v)$fail[]=$m;}
class BridgeStore implements BadpoolLiveCaptureEarningsStore {
	public $rows=array(),$earnings=array(),$other=array('blocks'=>'same','shares'=>'same','accounts'=>'same','payouts'=>'same','wallet'=>'same','candidates'=>'same','attributions'=>'same'),$failInsert=false;
	public function inventory($coin,$ids,$limit){$out=array();foreach($this->rows as $r)if($r['candidate_coin_id']==$coin&&(!$ids||in_array($r['block_id'],$ids)))$out[]=$r;usort($out,function($a,$b){return $a['block_id']-$b['block_id'];});return array_slice($out,0,$limit);}
	public function applyEarnings($rows,$expected){$before=$this->earnings;try{foreach($rows as $r)foreach($before as $e)if($e['blockid']==$r['blockid'])throw new RuntimeException('duplicate');foreach($rows as $r){$this->earnings[]=$r;if($this->failInsert)throw new RuntimeException('insert fail');}return array('inserted_count'=>count($rows),'block_count'=>count(array_unique(array_column($rows,'blockid'))));}catch(Exception $e){$this->earnings=$before;throw $e;}}
}
function row($id,$coin=1267,$attrs=null){if($attrs===null)$attrs=array(array('userid'=>8,'difficulty'=>3,'no_fees'=>0,'donation'=>0),array('userid'=>7,'difficulty'=>1,'no_fees'=>1,'donation'=>2));return array('block_id'=>$id,'candidate_coin_id'=>$coin,'candidate_algo'=>'scrypt','blockhash'=>'h'.$id,'found_time'=>1700000000+$id,'price'=>0.01,'share_floor_id'=>10,'share_ceiling_id'=>20,'block_exists'=>true,'block_coin_id'=>$coin,'block_algo'=>'scrypt','block_amount'=>8,'earnings_count'=>0,'attributions'=>$attrs);}
$s=new BridgeStore;$s->rows=array(row(27357),row(27358),row(27365,1267,array()),row(99,9));$b=new BadpoolLiveCaptureEarningsBridge($s,function($amount,$algo,$donation=null){return $donation===null?$amount*.99:$amount*(1-$donation/100);});
$r=$b->dryrun(1267,array(),2);ok($r['selected_block_ids']===array(27357,27358),'deterministic live-only limit');ok($r['eligible_count']===2&&count($r['projected_earnings_rows'])===4,'one row per user and block');ok($r['projected_earnings_rows'][0]['userid']===7&&$r['projected_earnings_rows'][0]['status']===0&&$r['projected_earnings_rows'][0]['mature_time']===null,'earning conventions');
$x=$b->dryrun(1267,array(27365,88888),25);ok($x['blocked_count']===2,'no attribution and unknown blocked');ok(in_array('blocked_no_attribution',$x['per_block_inventory'][0]['refusal_reasons']),'27365 empty span not payable');ok(in_array('unknown_or_non_live_block_id',$x['per_block_inventory'][1]['refusal_reasons']),'unknown selected refused');
$cases=array('missing_block'=>function(&$x){$x['block_exists']=false;},'block_coin_mismatch'=>function(&$x){$x['block_coin_id']=4;},'block_algo_mismatch'=>function(&$x){$x['block_algo']='sha256';},'already_has_earnings'=>function(&$x){$x['earnings_count']=1;},'non_positive_attribution_difficulty'=>function(&$x){$x['attributions'][0]['difficulty']=0;},'blocked_pending_block_amount'=>function(&$x){$x['block_amount']=null;});
foreach($cases as $reason=>$change){$t=new BridgeStore;$q=row(1);$change($q);$t->rows=array($q);$z=(new BadpoolLiveCaptureEarningsBridge($t,function($a){return $a;}))->dryrun(1267);ok(in_array($reason,$z['per_block_inventory'][0]['refusal_reasons']),$reason);}
$a=$b->approvalPackage(1267,array(27357),25);ok($a['approval_ready']&&$a['apply_command_shape']===BadpoolLiveCaptureEarningsBridge::applyCommandShape(),'approval package and exact command');$provided=array('selected_scope_checksum'=>$a['selected_scope_checksum'],'source_live_candidate_checksum'=>$a['source_live_candidate_checksum'],'attribution_checksum'=>$a['attribution_checksum'],'projected_earnings_checksum'=>$a['projected_earnings_checksum']);
foreach(array('bad checksum','bad confirmation') as $case){try{if($case==='bad checksum')$b->applyPackage($a,str_repeat('0',64),$provided,BadpoolLiveCaptureEarningsBridge::CONFIRMATION);else $b->applyPackage($a,$a['approval_package_checksum'],$provided,'no');ok(false,$case);}catch(Exception $e){ok(true,$case);}}
$before=$s->other;$applied=$b->applyPackage($a,$a['approval_package_checksum'],$provided,BadpoolLiveCaptureEarningsBridge::CONFIRMATION);ok($applied['inserted_count']===2&&count($s->earnings)===2,'only approved earnings committed');ok($s->other===$before,'unrelated state untouched');
try{$b->applyPackage($a,$a['approval_package_checksum'],$provided,BadpoolLiveCaptureEarningsBridge::CONFIRMATION);ok(false,'duplicate refused');}catch(Exception $e){ok(true,'duplicate refused');}
$drift=new BridgeStore;$drift->rows=array(row(4));$db=new BadpoolLiveCaptureEarningsBridge($drift,function($a){return $a;});$p=$db->approvalPackage(1267,array(4));$pp=array('selected_scope_checksum'=>$p['selected_scope_checksum'],'source_live_candidate_checksum'=>$p['source_live_candidate_checksum'],'attribution_checksum'=>$p['attribution_checksum'],'projected_earnings_checksum'=>$p['projected_earnings_checksum']);$drift->rows[0]['attributions'][0]['difficulty']=9;try{$db->applyPackage($p,$p['approval_package_checksum'],$pp,BadpoolLiveCaptureEarningsBridge::CONFIRMATION);ok(false,'drift refused');}catch(Exception $e){ok(empty($drift->earnings),'drift before mutation');}
$rollback=new BridgeStore;$rollback->rows=array(row(5));$rb=new BadpoolLiveCaptureEarningsBridge($rollback,function($a){return $a;});$p=$rb->approvalPackage(1267,array(5));$pp=array('selected_scope_checksum'=>$p['selected_scope_checksum'],'source_live_candidate_checksum'=>$p['source_live_candidate_checksum'],'attribution_checksum'=>$p['attribution_checksum'],'projected_earnings_checksum'=>$p['projected_earnings_checksum']);$rollback->failInsert=true;try{$rb->applyPackage($p,$p['approval_package_checksum'],$pp,BadpoolLiveCaptureEarningsBridge::CONFIRMATION);}catch(Exception $e){}ok(empty($rollback->earnings),'transaction rollback complete');
$stable1=$b->dryrun(1267,array(27357));$s->rows[0]['attributions']=array_reverse($s->rows[0]['attributions']);$stable2=$b->dryrun(1267,array(27357));ok($stable1['attribution_checksum']===$stable2['attribution_checksum']&&$stable1['projected_earnings_checksum']===$stable2['projected_earnings_checksum'],'order-independent checksums');
$source=file_get_contents(dirname(__FILE__).'/../web/yaamp/core/backend/BadpoolLiveCaptureEarningsBridge.php');foreach(array('INSERT INTO payouts','UPDATE blocks','UPDATE shares','UPDATE accounts','sendmany','WalletRPC','runBackend') as $bad)ok(stripos($source,$bad)===false,'separation '.$bad);
if($fail)throw new RuntimeException('FAIL: '.implode('; ',$fail));echo "PASS live capture earnings bridge harness\n";
