<?php
/** Exact-decimal funding authority. Configure externally, for example:
 * define('YAAMP_BADPOOL_MINIMUM_WALLET_RESERVES', array(1267 => '<operator-selected BAD amount>'));
 * Absence is deliberately different from explicitly configured zero. */
class BadpoolWalletFundingGuard
{
	const SCHEMA='badpool.wallet_funding.v1';
	public static function configuredReserve($coinId){if(!defined('YAAMP_BADPOOL_MINIMUM_WALLET_RESERVES'))return array('configured'=>false,'value'=>null,'error'=>'reserve policy is not configured');$p=constant('YAAMP_BADPOOL_MINIMUM_WALLET_RESERVES');if(!is_array($p)||!array_key_exists($coinId,$p))return array('configured'=>false,'value'=>null,'error'=>'reserve policy is not configured for coin');$v=$p[$coinId];if((!is_string($v)&&!is_int($v))||!self::isDecimal((string)$v))return array('configured'=>true,'value'=>null,'error'=>'reserve policy is malformed or negative');return array('configured'=>true,'value'=>self::normalize((string)$v),'error'=>null);}
	public static function evaluate($balance,$send,$policy){$r=array('wallet_balance'=>null,'wallet_send_total'=>null,'minimum_wallet_reserve'=>null,'required_wallet_balance'=>null,'projected_post_send_balance'=>null,'wallet_balance_read_success'=>false,'reserve_policy_configured'=>!empty($policy['configured']),'sufficient_for_send'=>false,'reserve_preserved'=>false,'funding_classification'=>'HOLD / WALLET BALANCE UNAVAILABLE');if(!self::isDecimal($send)){$r['funding_error']='wallet send total is malformed';return $r;}$r['wallet_send_total']=self::normalize($send);if(empty($policy['configured'])){$r['funding_classification']='HOLD / WALLET RESERVE POLICY UNCONFIGURED';$r['funding_error']=arraySafeVal($policy,'error');return $r;}if(!isset($policy['value'])||!self::isDecimal($policy['value'])){$r['funding_classification']='HOLD / WALLET RESERVE POLICY MALFORMED';$r['funding_error']=arraySafeVal($policy,'error','reserve policy is malformed or negative');return $r;}$r['minimum_wallet_reserve']=self::normalize($policy['value']);$r['required_wallet_balance']=self::add($r['wallet_send_total'],$r['minimum_wallet_reserve']);if((!is_string($balance)&&!is_int($balance))||!self::isDecimal((string)$balance)){$r['funding_error']='wallet balance response is unavailable or malformed';return $r;}$r['wallet_balance_read_success']=true;$r['wallet_balance']=self::normalize((string)$balance);$r['projected_post_send_balance']=self::subtract($r['wallet_balance'],$r['wallet_send_total']);$r['sufficient_for_send']=self::compare($r['wallet_balance'],$r['wallet_send_total'])>=0;$r['reserve_preserved']=self::compare($r['wallet_balance'],$r['required_wallet_balance'])>=0;$r['funding_classification']=$r['reserve_preserved']?'PASS / WALLET FUNDING SUFFICIENT':'HOLD / WALLET FUNDING INSUFFICIENT';return $r;}
	public static function isDecimal($v){return preg_match('/^\d+(?:\.\d+)?$/',(string)$v)===1;}
	public static function normalize($v){$p=explode('.',(string)$v,2);$w=ltrim($p[0],'0');if($w==='')$w='0';$f=isset($p[1])?rtrim($p[1],'0'):'';return $f===''?$w:$w.'.'.$f;}
	private static function scale($a,$b){$a=explode('.',(string)$a,2);$b=explode('.',(string)$b,2);return max(isset($a[1])?strlen($a[1]):0,isset($b[1])?strlen($b[1]):0);}
	private static function digits($v,$s){$p=explode('.',self::normalize($v),2);$d=ltrim($p[0].str_pad(isset($p[1])?$p[1]:'',$s,'0'),'0');return $d===''?'0':$d;}
	private static function format($d,$s){$d=ltrim($d,'0');if($d==='')$d='0';if(!$s)return $d;if(strlen($d)<=$s)$d=str_pad($d,$s+1,'0',STR_PAD_LEFT);return self::normalize(substr($d,0,-$s).'.'.substr($d,-$s));}
	public static function compare($a,$b){$s=self::scale($a,$b);$a=self::digits($a,$s);$b=self::digits($b,$s);if(strlen($a)!==strlen($b))return strlen($a)>strlen($b)?1:-1;return $a===$b?0:(strcmp($a,$b)>0?1:-1);}
	public static function add($a,$b){$s=self::scale($a,$b);$a=self::digits($a,$s);$b=self::digits($b,$s);$i=strlen($a)-1;$j=strlen($b)-1;$c=0;$o='';while($i>=0||$j>=0||$c){$n=$c+($i>=0?ord($a[$i--])-48:0)+($j>=0?ord($b[$j--])-48:0);$o=chr(48+$n%10).$o;$c=intdiv($n,10);}return self::format($o,$s);}
	public static function subtract($a,$b){if(self::compare($a,$b)<0)return '-'.self::subtract($b,$a);$s=self::scale($a,$b);$a=self::digits($a,$s);$b=str_pad(self::digits($b,$s),strlen($a),'0',STR_PAD_LEFT);$c=0;$o='';for($i=strlen($a)-1;$i>=0;$i--){$n=ord($a[$i])-48-$c-(ord($b[$i])-48);if($n<0){$n+=10;$c=1;}else$c=0;$o=chr(48+$n).$o;}return self::format($o,$s);}
}
